apiVersion: apps/v1
kind: Deployment
metadata:
  name: livraria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livraria
  template:
    metadata:
      labels:
        app: livraria
    spec:
      containers:
        - name: livraria
          image: luizeduardoardovino/livraria:latest
          ports:
            - containerPort: 8080  # Porta que o Livraria expõe

---
apiVersion: v1
kind: Service
metadata:
  name: livraria
spec:
  type: NodePort
  selector:
    app: livraria
  ports:
    - protocol: TCP
      port: 80  # Porta externa para acessar o serviço
      targetPort: 8080  # Porta dentro do container
