# Usando uma imagem base do OpenJDK 21
FROM openjdk:21-jdk-alpine

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o JAR gerado pelo Maven para o container
COPY target/autorservice-0.0.1-SNAPSHOT.jar autorservice.jar

# Expõe a porta em que o AutorService roda
EXPOSE 8081

# Comando para rodar o serviço
ENTRYPOINT ["java", "-jar", "autorservice.jar"]
