# Usando uma imagem base do OpenJDK 21
FROM openjdk:21-jdk-alpine

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o JAR gerado pelo Maven para o container
COPY target/livraria-0.0.1-SNAPSHOT.jar livraria.jar

# Expõe a porta em que o Livraria roda
EXPOSE 8080

# Comando para rodar o serviço
ENTRYPOINT ["java", "-jar", "livraria.jar"]
