name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v2

  
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

   
    - name: Build and push AutorService Docker image
      run: |
        docker build -t luizeduardoardovino/autorservice:latest ./autorservice/autorservice
        docker push luizeduardoardovino/autorservice:latest

    - name: Build and push Livraria Docker image
      run: |
        docker build -t luizeduardoardovino/livraria:latest ./livraria/livraria
        docker push luizeduardoardovino/livraria:latest

   
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'  # Altere essa versão conforme a versão do Kubernetes que você estiver usando

   
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/autorservice-deployment.yml
        kubectl apply -f k8s/livraria-deployment.yml
